version: '2'
services:
  nginx:
    image: nginx:1.10
    container_name: hangman_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
          - php-fpm

  php-fpm:
      image: php:7.0.6-fpm
      container_name: hangman_php-fpm
      ports:
        - "9000:9000"
      volumes:
        - ./:/var/www/html